version: "3.7"

services:
  flask:
    build:
      context: ./flask
    restart: always
    volumes:
      - ./flask:/app
    environment:
      - APP_NAME=MyFlaskApp

  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - "5000:80"
    depends_on:
      - flask
